version: 2
jobs:
  build-amd:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make GPU="--amd" all
  build-nvidia:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make GPU="--nvidia" all
  build-generic:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make GPU="--generic" all
  build-headless:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get -y install wget
      - run: sudo apt-get -y install unzip
      - run: make GPU="--headless" all
workflows:
  version: 2
  array_builds:
    jobs:
      - build-amd
      - build-nvidia
      - build-generic
      - build-headless

